AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "spec/dummy/**/*"
    - "config/initializers/devise.rb"
    - "config/initializers/simple_form.rb"
    - "config/initializers/simple_form_bootstrap.rb"

Metrics/LineLength:
  Max: 80

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: leading

StringLiterals:
  EnforcedStyle: double_quotes

StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
