language: ruby
bundler_args: --without development production --quiet
install: ruby -S bundle install
script:
  - bundle exec rake db:drop db:create db:migrate RAILS_ENV=test
  - bundle exec rspec spec
rvm:
  - 2.1
  - 2.2
